services:
  nutrition-api:
    container_name: nutrition-api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "6001:8000"
    volumes:
      - ./src:/nutrition-api/src
    depends_on:
      - db
    # Uncomment for PROD
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: nutrition-api-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6003:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "6002:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
